### ISSUE TITLE
abandon ?

### ISSUE THREAD

**Issue by jon100456** [FlibioStudio/SimpleScript#1]
Is this abandon ?

**Comment by liach** [comment]
Probably @Flibio just forgot this.

**Comment by jon100456** [comment]
Dang

**Comment by Flibio** [comment]
Like the [thread](https://forums.spongepowered.org/t/page-with-curl-0-3-0-simplescript-discontinued/12643/33), SimpleScript has been discontinued as of August 6, 2016.
